"""Sixth  Migration

Revision ID: 7d062032e565
Revises: f5ba0a32b255
Create Date: 2022-05-18 14:32:11.757566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d062032e565'
down_revision = 'f5ba0a32b255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'posted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('posted', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
