"""Fourth  Migration

Revision ID: f5ba0a32b255
Revises: cadfeea29133
Create Date: 2022-05-18 14:23:16.960943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ba0a32b255'
down_revision = 'cadfeea29133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'blog')
    # ### end Alembic commands ###
